[package]
name = "js-api"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.106"
exam-utils = { path = "../exam-utils" }
prisma = { path = "../prisma" }
